# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2122a611485e170011e30851c5aab62e750e82c71aca824e16722cd7566f16fd6aa3acb0a94690fdb2baadf897ccc60ef1e0cc57e72741c23687b72ad886c714

test:
  secret_key_base: 6c7a9a6a74783063601a1ca519783cead8b293e6eb4ba66c0559e0a44e03c1ecfa19c63be2de7e308fe1a8623553f04cda1273c5535dc2189df2aafcf31206cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
